/**
 * Writes supabase/seed.sql from data/seed/*.json so the data can be loaded by
 * pasting one file into the Supabase SQL editor. No terminal or service key
 * needed. Re-running the SQL upserts, so it's safe to paste again later.
 *
 *   npx tsx scripts/build-seed-sql.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parseSeed } from "../lib/data/seed-schema";

const dir = path.resolve(__dirname, "../data/seed");
const read = (f: string) => JSON.parse(readFileSync(path.join(dir, f), "utf8"));
const seed = parseSeed({
  seats: read("house_seats.json"),
  races: read("races.json"),
  candidates: read("candidates.json"),
  issues: read("issues.json"),
  scores: read("scores.json"),
  orgs: read("orgs.json"),
  endorsements: read("endorsements.json"),
});

function lit(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

function upsert<T extends object>(table: string, rows: T[], columns: (keyof T)[], conflict: string[]): string {
  if (rows.length === 0) return `-- ${table}: nothing to insert\n`;
  const cols = columns.map(String);
  const values = rows.map((r) => `  (${columns.map((c) => lit(r[c])).join(", ")})`).join(",\n");
  const updates = cols
    .filter((c) => !conflict.includes(c))
    .map((c) => `${c} = excluded.${c}`)
    .join(", ");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values}\non conflict (${conflict.join(", ")}) do update set ${updates};\n\n`;
}

let sql = `-- Generated by scripts/build-seed-sql.ts. Paste the whole file into the Supabase SQL editor and run it.
-- Run supabase/migrations/0001_init.sql first. Safe to re-run: existing rows are updated in place.
begin;

`;
sql += upsert("house_seats", seed.seats, ["id", "state", "district", "incumbent_name", "incumbent_party", "caucuses_with", "notes", "needs_review"], ["id"]);
sql += upsert("orgs", seed.orgs, ["id", "name", "url", "kind", "signal", "sort_order"], ["id"]);
sql += upsert("issues", seed.issues, ["id", "name", "description", "weight", "sort_order", "rubric", "active"], ["id"]);
sql += upsert(
  "races",
  seed.races,
  ["id", "office", "state", "district", "seat_id", "senate_class", "title", "election_date", "election_type", "rating", "incumbent_name", "incumbent_party", "is_open_seat", "why_it_matters", "notes", "tracked", "needs_review"],
  ["id"],
);
sql += upsert(
  "candidates",
  seed.candidates,
  ["id", "race_id", "name", "party", "is_incumbent", "status", "website", "bio", "fec_id", "dw_nominate", "photo_url", "notes", "sort_order", "needs_review"],
  ["id"],
);
sql += upsert("scores", seed.scores, ["candidate_id", "issue_id", "score", "evidence", "source_url", "provisional"], ["candidate_id", "issue_id"]);
sql += upsert("endorsements", seed.endorsements, ["candidate_id", "org_id", "note", "url"], ["candidate_id", "org_id"]);
sql += "commit;\n";

const out = path.resolve(__dirname, "../supabase/seed.sql");
writeFileSync(out, sql);
console.log(
  `wrote ${path.relative(process.cwd(), out)}: ${seed.seats.length} seats, ${seed.races.length} races, ${seed.candidates.length} candidates, ${seed.scores.length} scores, ${seed.endorsements.length} endorsements`,
);
